on:
  push:
    branches:
      - master

name: Build and deploy to GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: add books.json to output
        run: cp input/books.json static/books.json
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
